apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  template:
    spec:
      containers:
      - name: coffee-shop
        image: nexus-registry-nexus.apps.cluster-a423.dynamic.opentlc.com/user14-coffee-shop:prod-2021-08-17-18-19-50
                                                                                             

