---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: user14-prod-coffeeshop

patches:
- ./deployment-patches.yaml

configMapGenerator:
- name: coffee-shop
  envs:
  - ./configmap.env

